const stories=[
    {title:"Benny's Colorful Quest", image:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700924429/Interactive-Story-Book/image1_0_hfrrrg.jpg", story:[
        {passage:"Once upon a time, in a magical land called Storyville, there lived a curious little rabbit named Benny. ",bg:'https://res.cloudinary.com/dl3stdqmp/image/upload/v1700924429/Interactive-Story-Book/image1_0_hfrrrg.jpg',layout:"layout3"},
        {passage:"Once upon a time, in a magical land called Storyville, there lived a curious little rabbit named Benny. ",bg:'https://res.cloudinary.com/dl3stdqmp/image/upload/v1700924429/Interactive-Story-Book/image1_0_hfrrrg.jpg',layout:"layout1"},
        {passage:"Benny was known for his insatiable appetite for carrots and his love for exploring the enchanted forest that surrounded his burrow",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700925378/Interactive-Story-Book/image1_0_mtbjcd.jpg",layout:"layout2"},
        {passage:"",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700926785/Interactive-Story-Book/image1_0_t4ryip.jpg",layout:"layout3"},
        {passage:"One sunny morning, Benny hopped out of his burrow, his fluffy ears perked up with excitement. As he nibbled on a crisp carrot, he overheard a mysterious whispering sound coming from the heart of the forest. Intrigued, Benny decided to follow the gentle whispers, his paws pitter-pattering on the soft moss-covered ground. As Benny ventured deeper into the forest, the whispers grew louder, revealing themselves to be the magical trees sharing their ancient stories. One wise old oak tree spoke up, \"Greetings, Benny! We've been waiting for you. We have a special task for a brave and curious rabbit like yourself.\"Benny's eyes widened with curiosity. \"What is it?\" he asked, his nose twitching.",bg:"blue",layout:"layout4"},
        {passage:"The ancient oak explained that a mischievous pixie had hidden all the colors of the rainbow, and without them, the forest was starting to lose its magic.",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700927188/Interactive-Story-Book/image0_0_kbn5j4.jpg",layout:"layout5"},
        {passage:"Benny's mission was to find the colors and bring them back. Excited to embark on this colorful adventure, Benny hopped from one part of the forest to another. ",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700927188/Interactive-Story-Book/image0_0_kbn5j4.jpg",layout:"layout6"},
        {passage:"",bg:"",layout:"",option:{question:"How many colors are there in the rainbow?",options:["1","5","7"],answer:2, optionBG:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700929050/Interactive-Story-Book/image1_0_ychzmu.jpg"}},
        {passage:"Along the way, he met a chatty bluebird named Polly. \"Hey Benny, have you heard about the missing colors? I saw a red sparkle near the sparkling pond,\" Polly chirped.",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700929050/Interactive-Story-Book/image1_0_ychzmu.jpg",layout:"layout7"},
        {passage:"",bg:"https://res.cloudinary.com/dl3stdqmp/image/upload/v1700928921/Interactive-Story-Book/image0_0_jgnvqx.jpg",layout:"layout3"},
        ]},
];
export default stories;